name: 'Sous Paragraph Types'
description: 'A recipe that contains modules and configuration for the default Sous paragraph types.'
type: 'Site'
recipes:
  - sous-formats
  - sous-media
install:
  # Core modules
  - file
  - image
  - media
  - media_library
  - options
  - paragraphs
  - paragraphs_collapsible
  - paragraphs_ee
  - taxonomy
  - views
  # Contrib modules
  - focal_point
  - media_library_edit
